# Default values for application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  enabled: true
  className: ""
  annotations: 
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: argoapp-qa.projectxconsulting.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
  - secretName: argoapp-qa-tls
    hosts:
      - argoapp-qa.projectxconsulting.net

